name: Action Firebase Node
description: Setup the firebase-tools and run any command
author: Michel Courtine
inputs:
  tools-version:
    description: Version of firebase-tools to install
    required: false
  firebase_token:
    description: The token to use for authentication
    required: false
  gcp_sa_key:
    description: Service account key for authentication
    required: false
  project_id:
    description: Specify a specific project to use for all commands
    required: false
  project_path:
    description: Path to the folder containing firebase.json if it doesn't exist at the root of your repository
    required: false
branding:
  icon: 'activity'
  color: 'gray-dark'
runs:
  using: node16
  main: dist/setup/index.js
  post-if: success()